Create a catalog page
htmlacademy-adaptive/1462123-pink-21 pull request #4
Opened 2020-11-18 14:02 UTC by PIugai

2020-11-18 20:27 UTC, ant1quar requested changes

2020-11-18 20:27 UTC, ant1quar commented on source/catalog.html
> +        </li>
Это стоит вынести в отдельный блок - фотка ж полноразмерная, она вываливается из списка

2020-11-18 20:27 UTC, ant1quar commented on source/catalog.html
> +            <button class="post__likes likes" type="button"><span class="likes-number">Нравится: 356</span></button>
Зачем тут спан?

2020-11-18 20:27 UTC, ant1quar commented on source/catalog.html
> +            <button class="post__likes likes" type="button"><span class="likes-number">Нравится: 356</span></button>
И почему нет сердечка? 
мне кажется, button это сердце, а span должен быть отдельно

2020-11-18 20:27 UTC, ant1quar commented on source/catalog.html
> +      </form>
Тут чуть недоработано. - сделай тягалки через `label` и `input type="number"`

2020-11-19 02:45 UTC, PIugai commented on source/catalog.html
> +      </form>
А Range пойдет?

2020-11-19 08:28 UTC, merged